FROM ghcr.io/actions/actions-runner:2.336.0

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends podman netavark aardvark-dns iptables build-essential python3-dev \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /etc/containers \
    && printf '[storage]\ndriver = "vfs"\nrunroot = "/run/containers/storage"\ngraphroot = "/var/lib/containers/storage"\n' > /etc/containers/storage.conf
