apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-htpass-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: htpass-secret
  data:
    - secretKey: htpasswd
      remoteRef:
        key: SAKAAR_OCP_ADMIN_HTPASSWD
