githubConfigUrl: "https://github.com/PixelJonas/tax-agent"
githubConfigSecret: arc-runner-set-tax-agent-github-secret
runnerScaleSetName: "arc-runner-set-tax-agent"
minRunners: 0
maxRunners: 3
controllerServiceAccount:
  namespace: actions-runner-system
  name: arc-gha-rs-controller
containerMode: {}
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/pixeljonas/sakaar-gha-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: RUNNER_ALLOW_RUNASROOT
            value: "1"
        securityContext:
          privileged: true
          runAsUser: 0
